name: Deploy master branch
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: npm install and build
        working-directory: ${{ github.workspace }}
        run: |
          npm install
          npm run build
      - name: Run ls on workplace
        run: |
          ls -alR ${{ github.workspace }}

      - name: serverless deploy
        uses: serverless/github-action@master
        # working-directory: ${{ github.workspace }}
        with:
          args: -c "serverless plugin install --name serverless-finch && echo "y" | serverless client deploy"
          entrypoint: /bin/sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
